version: "3.9"

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=p_db
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_password
    ports: 
     - 5432:5432

  migration:
    image: igorturist/ybs_task:0.1.0
    command: /usr/share/python3/ybs_task/wait-for-it.sh -t 4 db:5432 -- python3.8 /usr/share/python3/ybs_task/ybs_task/bin/manage.py migrate
    environment:
      - POSTGRES_DB=p_db
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_password
      - DB_HOST=db
    ports:
      - 8001:8001
    depends_on:
      - db

  web:
    build: .
    image: igorturist/ybs_task:0.1.0
    restart: always
    command: /usr/share/python3/ybs_task/wait-for-it.sh -t 4 migration:8001 -- python3.8 /usr/share/python3/ybs_task/ybs_task/bin/manage.py runserver '0.0.0.0:80'
    environment:
      - POSTGRES_DB=p_db
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_password
      - DB_HOST=db
    ports:
      - 80:80
    depends_on:
      - db
      - migration

  test:
    image: igorturist/ybs_task:0.1.0
    command: /usr/share/python3/ybs_task/wait-for-it.sh -t 4 web:80 -- python3.8 /usr/share/python3/ybs_task/ybs_task/bin/manage.py test prices_comparator.tests
    environment:
      - POSTGRES_DB=p_db
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_password
      - DB_HOST=db
      - WEB_HOST=http://web
    depends_on:
      - web
