version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=p_db
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_password
    ports: 
     - 5432:5432
  app:
    # restart: always
    build: .
    command: python3.8 /usr/share/python3/ybs_task/ybs_task/bin/manage.py runserver '0.0.0.0:80'
    environment:
      - POSTGRES_DB=p_db
      - POSTGRES_USER=p_user
      - POSTGRES_PASSWORD=p_password
      - DB_HOST=db
    ports:
      - 80:80
    depends_on:
      - db




